version: '3.7'

services: 
    app:
        container_name: savics_datatocare
        restart: always
        build: .
        ports:
            - '5000:3000'
        links: 
            - db
        depends_on: 
            - db
    db:
        container_name: postgres
        image: postgres
        ports: 
            - '3838:5432'

        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=savics

        volumes: 
            - ./pgdata:/var/lib/postgresql/data